[tool.black]
line_length = 120

[tool.mypy]
python_version = "3.10"

disallow_untyped_defs = true
no_warn_return_any = true
no_strict_optional = true
ignore_missing_imports = true
no_warn_no_return = true

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120